global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "pz-mgmtd"
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
          - "localhost:443"

  - job_name: "node_exporter"
    static_configs:
      - targets:
          - "localhost:9100"
